version: '3'

services:
  api:
    container_name: pinguim-api
    build: .
    command: npm run dev
    ports:
      - '3333:3333'
    env_file:
      - .env
    volumes:
      - .:/home/node/app
    links:
      - database

  database:
    container_name: pinguim-database
    image: mysql:5.7.32
    environment:
      - MYSQL_DATABASE=pinguim
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=123mudar
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_INITDB_SKIP_TZINFO=true
      - TZ=America/Sao_Paulo
    volumes:
      - database:/var/lib/mysql
    ports:
      - '3307:3306'

volumes:
  database:
