apiVersion: v1
kind: Service
metadata:
  name: pinguim-nest-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: pinguim-nest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3333
      name: pinguim-nest
