apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pinguim-nest-hpa
  namespace: dev
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pinguim-nest-deployment
  targetCPUUtilizationPercentage: 85
