apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-web-deployment
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nest-web
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "3333"
    spec:
      containers:
        - name: nest-web
          image: IMAGE_VERSION
          ports:
            - containerPort: 3333
              protocol: TCP
          resources:
            requests:
              cpu: 300m
              memory: 900Mi
            limits:
              cpu: 600m
              memory: 1500Mi
      affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - nest-web
                  topologyKey: kubernetes.io/hostname
                weight: 100
