apiVersion: v1
kind: Service
metadata:
  name: nest-web-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: nest-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3333
      name: nest-web
