apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nest-web-hpa
  namespace: prod
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nest-web-deployment
  targetCPUUtilizationPercentage: 85
